version: '3'
services:
   db:
      image: mongodb
      ports:
         - "27017:27017"
      volumes:
         - "./mongodata:/data/db"
   web:
      build: .
      ports: 
         - 8080:8080
      depends_on:
         - mongodb